import { StyleSheet, Platform, Dimensions } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    alignContent: 'center',
    justifyContent: 'space-around',
    padding: 20,
    backgroundColor: 'white',
  },
  title: {
    fontSize: 34,
    textAlign: 'center',
    marginVertical: 8,
    color: '#4A4B57',
  },
  welcomeContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: 300,
    marginLeft: -20,
    // alignItems: 'center',
  },
  greeting: {
    fontSize: 24,
    textAlign: 'center',
    marginVertical: 8,
    color: '#2B3674',
    fontWeight: '600',
  }, 
  motivation: {
    fontSize: 20,
    textAlign: 'center',
    marginVertical: 8,
    color: '#4A4B57',
    fontWeight: '400',
    marginLeft: -20,
  },
  name: {
    fontSize: 24,
    textAlign: 'center',
    marginVertical: 8,
    color: '#008AFC',
    fontWeight: '600',
  },
  squareButton: {
    width: Platform.OS === 'ios' && Platform.isPad ? 150 : 99,
    height: Platform.OS === 'ios' && Platform.isPad ? 150 : 99,
    backgroundColor: 'white',
    borderColor: '#005AA3',
    borderWidth: 5,
    borderRadius: 25,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerButton: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 35,
  },
  bodyContainer: {},
  footerContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 10,
    marginRight: 10,
    paddingBottom: 20,
  },
  footerTextSelected: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2B3674',
  },
  footerTextUnselected: {
    fontSize: 16,
    fontWeight: '500',
    color: '#9CA5C2',
  },
  buttonsContainer: {
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'space-around',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'stretch',
  },
  buttonTitle: {
    alignSelf: 'center',
    fontWeight: 'bold',
    color: 'white',
  },
  squareButtonTitle: {
    alignSelf: 'center',
    fontSize: 20,
    fontWeight: '400',
  },
  imageContainer: {
    flex: 2,
    width: '100%',
    height: 150,
    borderRadius: 2,
    flexDirection: 'column',
    padding: 8,
  },
  image: {
    alignSelf: 'center',
    width: Dimensions.get('window').width - 50,
    height:
      Platform.OS === 'ios' && Platform.isPad
        ? 400
        : Dimensions.get('window').height * 0.15,
    resizeMode: 'contain',
  },
  icon: {
    fontSize: Platform.OS === 'ios' && Platform.isPad ? 60 : 45,
  },
});

export const streakStyles = {
  stepIndicatorSize: 30,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 8,
  separatorStrokeUnfinishedWidth: 8,
  separatorStrokeFinishedWidth: 8,
  stepStrokeWidth: 0,
  currentStepStrokeWidth: 5,
  stepStrokeCurrentColor: '#005AA3',
  stepStrokeFinishedColor: '#005AA3',
  stepStrokeUnfinishedColor: '#005AA3',
  separatorFinishedColor: '#005AA3',
  separatorUnFinishedColor: '#dbdbdb',
  stepIndicatorFinishedColor: '#005AA3',
  stepIndicatorUnFinishedColor: '#dbdbdb',
  stepIndicatorCurrentColor: '#ffffff',
  stepIndicatorLabelFontSize: 15,
  currentStepIndicatorLabelFontSize: 15,
  stepIndicatorLabelCurrentColor: '#000000',
  stepIndicatorLabelFinishedColor: '#ffffff',
  stepIndicatorLabelUnfinishedColor: '#000000',
};
