version: "3.8"
services:
  mobile:
    container_name: brain-exercise-mobile
    build:
      context: .
      target: dev
    restart: always
    entrypoint: ./entrypoint.sh
    platform: linux/amd64
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    env_file:
      - bitwarden.env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
